version: "4.0"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      target: development
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3000
