version: "3.8"

services:
  app:
    container_name: app-prod
    image: app-prod
    build:
      target: production
    environment:
      CHOKIDAR_USEPOLLING: "true"

# To Create Build  (command) docker-compose -f .\docker-compose.prod.yml build
# to run build (command) docker run -p 80:80 react-app --name app-prod
